import type { Metadata } from "next";
import "./globals.css";
import UserProvider from "./context/user";
import AllOverlays from "./components/AllOverlay";



export const metadata: Metadata = {
  title: "TikTok Clone",
  description: "Generated by Tahreem Zafar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
      <body>
         <AllOverlays />
        {children}
      </body>
      </UserProvider>
    </html>
  );
}
